### ISSUE TITLE
Gets error message while trying to add photo on screen rotation

### ISSUE THREAD

**Issue by Olamatto** [cohenadair/anglers-log#302] opened 2018-05-30 02:19 UTC
#### Expected behavior
App is expected to work perfectly well on any screen orientation. 

#### Actual Behavior 
While trying to add photo on screen rotation, I get an error message, not being able to save photo.

#### How to reproduce
- Download and install the application [here](https://play.google.com/store/apps/details?id=com.cohenadair.anglerslog)
- Launch the application 
- Click on the menu button, by the top right
- Select Catches
- Click on the add button 
- Click on Add Photo 
- Select Attach Photos
- Rotate your screen
- Select the picture 

And the error message comes in "Error in saving photo"

<hr>

Application version: v 1.2.10
Operating system: Android v7.0

#### Recording Of The Bug
https://youtu.be/AZLSpNwiUpg

**Comment by cohenadair** [comment] 2018-05-30 04:05
Related to, possibly a duplicate of #301.

**Comment by cohenadair** [comment] 2018-05-30 04:06
Closing, as this will be resolved in Anglers' Log 2.0.

**Closed by cohenadair** 2018-05-30 04:06 UTC
Labels: android, bug
